gemini_service_server:
  ros__parameters:
    capacity: "\
      "
    role: "\
      "
    insight: "\
      "
    statement: "\
      [指示]\
      出力にはMarkdown形式は使用しないでください。\
      物体名だけで出力を依頼された場合は、物体名だけを出力するようにしてください。\
      出力内容と形式に関しては[Prompt]に従ってください
      "
    personality: "\
      "
    Experiment: "\
      "
